### ISSUE TITLE
Add Start Menu and Saves

### ISSUE THREAD

**Issue by nohbdy-exe** [nohbdy-exe/teamblackarch#15]
As a player, I want to be able to pause my game and save it so I can start from a checkpoint

**Comment by brdiekmann** [comment]
I pushed some more to my branch that has a Scene set up as a possible pause menu screen (nothing on it is functioning just a UI layout). The main focus of the push was the actual pause mechanic when the user presses the 'esc' key it will pause the moving components in the game and disable the camera from moving and when 'esc' is pressed again it will resume everything
